### ISSUE TITLE
[v2.1][FEATURE] Tạo mới hồ sơ có đính kèm biểu mẫu

### ISSUE THREAD

**Issue by gunrosen** [VietOpenCPS/opencps-v2#1071]
Thành phần hồ sơ nên đính kèm luôn biểu mẫu tương ứng. Hiện tại phải sang danh sách thủ tục hành chính để tải biểu mẫu (.doc)

**Comment by hmtuong2705** [comment]
Hiện nay hệ thống chưa hỗ trợ việc này và sẽ bổ sung vào tại bước hoàn thiện phần mềm.
