### ISSUE TITLE
[v2.1][FEATURE] Màn hình Kiosk phục vụ tra cứu hồ sơ

### ISSUE THREAD

**Issue by gunrosen** [VietOpenCPS/opencps-v2#1234]
![photo6291935335986342009 1](https://user-images.githubusercontent.com/3174484/43816420-dd4bae86-9afe-11e8-8542-a932d2301fc1.jpg)

**Comment by pmfds** [comment]
![02 2 kios - ket qua](https://user-images.githubusercontent.com/41315179/44319973-79653f80-a469-11e8-8dd3-0d373756cbd2.png)
![02 3 kios - tra c u h s](https://user-images.githubusercontent.com/41315179/44319974-79653f80-a469-11e8-9264-86778af3a781.png)
![02 4 kios - tra c u th t c](https://user-images.githubusercontent.com/41315179/44319975-79653f80-a469-11e8-9c45-5a6356c5fcb7.png)
![02 5 kios - danh gia](https://user-images.githubusercontent.com/41315179/44319976-79fdd600-a469-11e8-86ca-da3fda369b13.png)
![02 6 kios - chi ti t danh gia](https://user-images.githubusercontent.com/41315179/44319977-79fdd600-a469-11e8-8d45-4b328639f283.png)
