### ISSUE TITLE
[BUG] Không thể sửa thông tin tài khoản

### ISSUE THREAD

**Issue by gunrosen** [VietOpenCPS/opencps-v2#1470]
Không có nút lưu 
![screen shot 2018-09-28 at 09 34 44](https://user-images.githubusercontent.com/3174484/46184852-ab3bb280-c301-11e8-81e9-291a59964aeb.png)

**Comment by dangkhanhtrung** [comment]
Chỉ cho phép sửa đổi thông tin chứng thư để ký số các thông tin khác không sửa đổi. Tệp chứng thư tải lên sẽ tự động được lưu lại.
