### ISSUE TITLE
Lỗi cấu hình thanh toán

### ISSUE THREAD

**Issue by laikimthanh** [VietOpenCPS/opencps-v2#732]
Hiện tại Phần cấu hình thanh toán chỉ cho phép cấu hình thanh toán tài khoản của 1 tổ chức, k hiển thị danh sách các cấu hình thanh toán với các tổ chức khác.

**Comment by khoahp** [comment]
@tranvietlam92

**Comment by khoahp** [comment]
@laikimthanh giải thích lại nhé

**Comment by DTThuyCMC** [comment]
okie, nhờ @laikimthanh close giúp chị issue này
