### ISSUE TITLE
Cổng xử lý _TK cán bộ _ Navigation hiển thị  cả trạng thái chính

### ISSUE THREAD

**Issue by laikimthanh** [VietOpenCPS/opencps-v2#733]
Navigation của cán bộ hiện tại hiển thị cả trạng thái chính và trạng thái phụ vì thế xảy ra trường hợp 1 hồ sơ thuộc cả 2 danh sách trên

**Comment by khoahp** [comment]
@laikimthanh em chụp cho anh cái hình navigator nhé không cho header và footer vào

**Comment by laikimthanh** [comment]
![image](https://user-images.githubusercontent.com/36915722/36779292-1780f024-1ca2-11e8-9447-cf74eaaddf56.png)

**Comment by khoahp** [comment]
@hoanganh16091995

**Comment by tranvietlam92** [comment]
@khoahp @laikimthanh  Bug này fix xong rồi nhé.
@laikimthanh  chị test lại giúp em nhé.

**Comment by laikimthanh** [comment]
@tranvietlam92  những cái cần test lỗi e báo c Thủy CMC nhé.

**Comment by tranvietlam92** [comment]
@khoahp vì cái bug này do chị Thanh log nên em không add đc chị Thủy vào ạ.

**Comment by DTThuyCMC** [comment]
đã test, ok
