### ISSUE TITLE
Từ cổng tiếp nhận chuyển cổng xử lý: cổng xử lý không hiển thị được các file attach chuyển sang

### ISSUE THREAD

**Issue by DTThuyCMC** [VietOpenCPS/opencps-v2#734]
trên cổng tiếp nhận: đã attach các file thành phần hồ sơ nộp. khi chuyển sang cổng xử lý: không thấy các file này

**Comment by khoahp** [comment]
@tranvietlam92 check isNew field in dossierFile when call API add dossierFile

**Comment by khoahp** [comment]
@tranvietlam92 báo lại thông tin phân này với nhé

**Comment by tranvietlam92** [comment]
@DTThuyCMC @khoahp  Bug này em fix xong từ hôm trước rồi nhé

**Comment by DTThuyCMC** [comment]
test ok
