### ISSUE TITLE
Hồ sơ đã từ chối trên cổng xử lý (kết thúc quy trình) nhưng trên cổng tiếp nhận không hiển thị trong mục <Hồ sơ đã kết thúc>

### ISSUE THREAD

**Issue by DTThuyCMC** [VietOpenCPS/opencps-v2#736]
trên cổng xử lý: tại bước tiếp nhận hồ sơ chọn <Hồ sơ không hợp lệ> -> kết thúc quy trình
Trên cổng tiếp nhận: hồ sơ không hiển thị trong mục <hồ sơ đã kết thúc> --> Yêu cầu: Khi đã kết thúc quy trình thì hiển thị hồ sơ tại mục <Hồ sơ đã kết thúc>
<img width="743" alt="ho so ket thuc" src="https://user-images.githubusercontent.com/36916049/36780958-1c546f0e-1ca7-11e8-8cec-8027021cf8a7.png">

**Comment by khoahp** [comment]
@laikimthanh em xem phần lại phần cấu hình các rổ trạng thái và trao đổi lại với chị Thủy nhé, nếu việc cấu hình không đáp ứng được sẽ review lại chức năng này

**Comment by DTThuyCMC** [comment]
@khoahp phần này vẫn lỗi nhé, hồ sơ từ chối không thấy hiển thị trong mục hồ sơ đã kết thúc

**Comment by DTThuyCMC** [comment]
test ok
