### ISSUE TITLE
Cổng xử lý: không view được nội dung tài liệu (đơn đăng ký nhập trên cổng tiếp nhận)

### ISSUE THREAD

**Issue by DTThuyCMC** [VietOpenCPS/opencps-v2#741]
cổng xử lý: cán bộ xử lý không view được nội dung đơn đăng ký đã nhập trên cổng tiếp nhận
<img width="835" alt="view tai lieu" src="https://user-images.githubusercontent.com/36916049/36886783-9450fe12-1e20-11e8-8b7e-461ec731583a.png">

**Comment by tranvietlam92** [comment]
@DTThuyCMC @khoahp em fix xong Bug này rồi nhé.
@DTThuyCMC  chị test lại giúp em nhé.

**Comment by DTThuyCMC** [comment]
ok
