### ISSUE TITLE
Cổng tiếp nhận: mục <Hồ sơ đang thực hiện> chỉ hiển thị hồ sơ có trạng thái chính là <chờ tiếp nhận>

### ISSUE THREAD

**Issue by DTThuyCMC** [VietOpenCPS/opencps-v2#743]
Cổng tiếp nhận: mục <Hồ sơ đang thực hiện> chỉ hiển thị hồ sơ có trạng thái chính là <chờ tiếp nhận>, các hồ sơ có trạng thái chính <đang giải quyết> không thấy hiển thị ở mục này --> cần hiển thị hồ sơ có trạng thái chính Đang giải quyết trong mục <hồ sơ đang thực hiện> trên cổng tiếp nhận
<img width="732" alt="ho so dang thuc hien" src="https://user-images.githubusercontent.com/36916049/36889826-3ebd369c-1e2e-11e8-8d13-21414d4e87ec.png">

**Comment by khoahp** [comment]
@DTThuyCMC trao đổi lại với @hoanganh16091995 xem hiển thị những trạng thái nào cần hiển thị

**Comment by tranvietlam92** [comment]
@DTThuyCMC chị thủy check lại giúp em bug này nhé

**Comment by DTThuyCMC** [comment]
test ok
