### ISSUE TITLE
Cổng xử lý: Hồ sơ nhận bổ sung không xử lý tiếp được

### ISSUE THREAD

**Issue by DTThuyCMC** [VietOpenCPS/opencps-v2#744]
- cổng tiếp nhận bổ sung hồ sơ --> cổng tiếp nhận: tiếp nhận hồ sơ bổ sung và chuyển thẩm định
- cán bộ vào mục <chờ thẩm định> để xử lý hồ sơ: hệ thống thông báo "hồ sơ chờ đồng bộ" và ko xử lý tiếp được
<img width="934" alt="cho dong bo" src="https://user-images.githubusercontent.com/36916049/36890751-a8a208aa-1e31-11e8-942c-f9b9b9f8951d.png">

**Comment by tranvietlam92** [comment]
@DTThuyCMC  @khoahp  em đang xử lý các bug này nhé.

**Comment by tranvietlam92** [comment]
@DTThuyCMC @khoahp Bug này xử lý xong rồi nhé.

**Comment by DTThuyCMC** [comment]
đã test lại, vẫn lỗi

**Comment by DTThuyCMC** [comment]
cấu hình lại ok
