### ISSUE TITLE
Cổng tiếp nhận: Hồ sơ hoàn thành không hiển thị các file kết quả

### ISSUE THREAD

**Issue by DTThuyCMC** [VietOpenCPS/opencps-v2#746]
hồ sơ hoàn thành bên cổng xử lý, trả kết quả về cổng tiếp nhận, tại cổng tiếp nhận mục Kết quả: ko hiển thị các file kết quả .
hiển thị khoảng trống phía dưới đơn đề nghị 
<img width="960" alt="ho so hoan thanh" src="https://user-images.githubusercontent.com/36916049/36957471-3c87bd44-2067-11e8-8ecd-cbe97f5f9d8a.png">

**Comment by khoahp** [comment]
@hoanganh16091995 tìm lỗi về phần khoảng trắng sau form khai, xem xem đây là nội dung của form động hay là đoạn thừa trong giao diện.

**Comment by DTThuyCMC** [comment]
test ok
