### ISSUE TITLE
Cổng xử lý: khi cấu hình thao tác, chọn tài liệu tạo mới/kết quả trả về: list hiển thị tất cả thành phần/kết quả của tất cả các mẫu hồ sơ

### ISSUE THREAD

**Issue by DTThuyCMC** [VietOpenCPS/opencps-v2#748]
cần xem lại vì hiển thị tất cả thì người cấu hình ko biết chọn thế nào cho đúng
<img width="765" alt="tao thao tac" src="https://user-images.githubusercontent.com/36916049/36966882-c9e02ae0-2090-11e8-87fc-f785adfad709.png">

**Comment by khoahp** [comment]
@hoanganh16091995 xử lý nhé

**Comment by khoahp** [comment]
@DTThuyCMC phần cấu hình dịch vụ công, khi chọn file trả về nó sẽ lọc toàn bộ file trên hệ thống, nếu file cấu hình trùng tên giữa các quy trình sẽ hiển thị ra như vậy.

Cách các dự án cấu hình là cập nhật thêm một prefix cho tên văn bản vd: QT01 - NameOfDocument

**Comment by DTThuyCMC** [comment]
Cần xem lại giải pháp, trên 1.8 không thêm prefix

**Comment by DTThuyCMC** [comment]
ok
