### ISSUE TITLE
Cổng tiếp nhận: tạo mới hồ sơ, sau khi chọn <Lưu>, các thông tin đã nhập ở đơn bị reset trắng

### ISSUE THREAD

**Issue by DTThuyCMC** [VietOpenCPS/opencps-v2#751]
người dùng nhập thông tin đơn và chọn <ghi lại>, hệ thống báo thành công
người dùng chọn <lưu> để lưu thông tin hồ sơ
--> các thông tin đã nhập trên đơn bị reset trắng
<img width="786" alt="luu ho so" src="https://user-images.githubusercontent.com/36916049/37072271-1cfa9630-21f3-11e8-9e87-3b2cf0a0c3f5.png">

**Comment by tranvietlam92** [comment]
@DTThuyCMC chị check lại giúp em đã chắc là GHI LẠI chưa nhé.
Em check thì không có hiện tượng như trên.
