### ISSUE TITLE
cổng xử lý: <Ý kiến> hiển thị chưa đúng

### ISSUE THREAD

**Issue by DTThuyCMC** [VietOpenCPS/opencps-v2#762]
thủ tục: Cấp giấy phép đủ điều kiện kinh doanh sản xuất phim
<img width="926" alt="bo sung tu dong" src="https://user-images.githubusercontent.com/36916049/37144158-c9cdfcd8-22ef-11e8-8ea0-6b791ff5eabc.png">

**Comment by khoahp** [comment]
@hoanganh16091995

**Comment by tranvietlam92** [comment]
@DTThuyCMC test lại giúp em bug này nhé

**Comment by TTMinh** [comment]
ok rồi anh nhé!
