### ISSUE TITLE
cổng xử lý: không load được form giấy chứng nhận

### ISSUE THREAD

**Issue by DTThuyCMC** [VietOpenCPS/opencps-v2#764]
<img width="959" alt="form" src="https://user-images.githubusercontent.com/36916049/37186672-38f6e9b0-2379-11e8-8416-e9583b6577a5.png">

**Comment by tranvietlam92** [comment]
@DTThuyCMC bug nay em fix xong rồi. chị test lại giúp em

**Comment by TTMinh** [comment]
ok rồi nhé
