### ISSUE TITLE
Cổng xử lý: thời gian hiển thị ko đúng, trường <ghi chú> bị duplicate

### ISSUE THREAD

**Issue by DTThuyCMC** [VietOpenCPS/opencps-v2#773]
<img width="698" alt="thoi gian" src="https://user-images.githubusercontent.com/36916049/37263870-ca7cc78c-25dc-11e8-8cc1-9e3ae4291677.png">

**Comment by tranvietlam92** [comment]
@DTThuyCMC bug này em fix ok rồi nhé

**Comment by DTThuyCMC** [comment]
test ok
