### ISSUE TITLE
Cổng xử lý: không load được form đơn đề nghị

### ISSUE THREAD

**Issue by DTThuyCMC** [VietOpenCPS/opencps-v2#778]
thủ tục: Cấp phép phổ biến tác phẩm sáng tác trước năm 1975 hoặc tác phẩm của người Việt Nam đang sinh sống và định cư ở nước ngoài
bước: tiếp nhận và thẩm định hồ sơ, chọn view đơn đề nghị, hệ thống báo lỗi
<img width="935" alt="load don de nghi" src="https://user-images.githubusercontent.com/36916049/37274412-0a830b7a-260f-11e8-9de6-392ea3a0f9aa.png">

**Comment by tranvietlam92** [comment]
@DTThuyCMC  bug này em fix ok rồi nhé

**Comment by DTThuyCMC** [comment]
test ok
