### ISSUE TITLE
cổng tiếp nhận: tìm theo lĩnh vực không hiển thị đủ dịch vụ công

### ISSUE THREAD

**Issue by DTThuyCMC** [VietOpenCPS/opencps-v2#782]
Dịch vụ: "Cấp phép phổ biến tác phẩm sáng tác trước năm 1975 hoặc tác phẩm của người Việt Nam đang sinh sống và định cư ở nước ngoài". Tìm theo lĩnh vực ko hiển thị dịch vụ công này
<img width="785" alt="dv50" src="https://user-images.githubusercontent.com/36916049/37320220-3a4c2cce-26a5-11e8-88e2-6ae76e48222e.png">

**Comment by tranvietlam92** [comment]
@DTThuyCMC bug này em fix ok rồi nhé

**Comment by DTThuyCMC** [comment]
test ok
