### ISSUE TITLE
cổng xử lý: ngày lập phiếu thanh toán ko hiển thị

### ISSUE THREAD

**Issue by DTThuyCMC** [VietOpenCPS/opencps-v2#785]
<img width="960" alt="thanh toan" src="https://user-images.githubusercontent.com/36916049/37328095-6ad99a9a-26cb-11e8-9074-6ac8691d2345.png">

**Comment by tranvietlam92** [comment]
@DTThuyCMC chị test lại giúp em nhé

**Comment by TTMinh** [comment]
ok nhé
